export const POKEMON_TYPE_SPANISH: Record<string, string> = {
  bug: 'Bicho',
  dark: 'Siniestro',
  dragon: 'Dragón',
  electric: 'Eléctrico',
  fairy: 'Hada',
  fighting: 'Lucha',
  fire: 'Fuego',
  flying: 'Volador',
  ghost: 'Fantasma',
  grass: 'Planta',
  ground: 'Tierra',
  ice: 'Hielo',
  normal: 'Normal',
  poison: 'Veneno',
  psychic: 'Psíquico',
  rock: 'Roca',
  shadow: 'Sombra',
  steel: 'Acero',
  unknown: 'Desconocido',
  water: 'Agua',
}
