export const POKEMON_TYPE_SPANISH: Record<string, string> = {
  bug: 'Bicho',
  dark: 'Siniestro',
  dragon: 'Dragón',
  electric: 'Eléctrico',
  fairy: 'Hada',
  fighting: 'Lucha',
  fire: 'Fuego',
  flying: 'Volador',
  ghost: 'Fantasma',
  grass: 'Planta',
  ground: 'Tierra',
  ice: 'Hielo',
  normal: 'Normal',
  poison: 'Veneno',
  psychic: 'Psíquico',
  rock: 'Roca',
  shadow: 'Sombra',
  steel: 'Acero',
  unknown: 'Desconocido',
  water: 'Agua',
}

export const POKEMON_TYPE_COLOR: Record<string, string> = {
  bug: '#a6b91a',
  dark: '#705746',
  dragon: '#6f35fc',
  electric: '#f7d02c',
  fairy: '#d685ad',
  fighting: '#c22e28',
  fire: '#ee8130',
  flying: '#a98ff3',
  ghost: '#735797',
  grass: '#7ac74c',
  ground: '#e2bf65',
  ice: '#96d9d6',
  normal: '#a8a77a',
  poison: '#a33ea1',
  psychic: '#f95587',
  rock: '#b6a136',
  shadow: '#333333',
  steel: '#b7b7ce',
  unknown: '#68a090',
  water: '#6390f0',
}
